baseURL = "https://saintmalik.me"
languageCode = "en-us"
title = "SaintMalik"
paginate     = 10
googleAnalytics = "UA-123518521-4"
disqusShortname = "myfoliosite"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  ProfilePicture = "../images/saintmalik.jpg"

  # Subtitle for home
  homeSubtitle = "Penetration tester and Aspiring Security Analyst."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "SaintMalik | Cyber Security Analyst | Bug Bounty Hunter | Penetration Tester | Bash, JavaScript, Vue.js | Security Analyst"
  images = [""]

  enableRobotsTXT = true
  enableGitInfo   = false
  enableEmoji     = true
  enableMissingTranslationPlaceholders = false
  disableRSS     = false
  disableSitemap = false
  disable404     = false

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#151515"
  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""
  
  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [""]
  customJS  = []

[author]
  name = "SaintMalik"

[permalinks]
  posts = "/:slug"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "SaintMalik"
    subtitle = "Cyber Security Analyst, Penetration Tester and Front-End Developer"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"
    
    [languages.en.params.logo]
      logoText = "~/saintmalik"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    # Social icons
  [[languages.en.params.social]]
    name = "twitter"
    url  = "https://twitter.com/saintmalik_"

  [[languages.en.params.social]]
    name = "email"
    url  = "mailto:@gmail.com"

  [[languages.en.params.social]]
    name = "github"
    url  = "https://github.com/saintmalik"

    # You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Who am i"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "works"
        name = "Works"
        url = "/works"
          
# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "who am i"
    name       = "Who am i"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "works"
    name       = "Works"
    url        = "/works"
